src/CoreBundle/Entity/Enclosure.php
<?php declare(strict_types=1);

namespace App\CoreBundle\Entity;

use App\CoreBundle\Exception\DinosaursAreRunningRampantException;
use App\CoreBundle\Exception\NotABuffetException;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\CoreBundle\Repository\EnclosureRepository")
 * @ORM\Table(name="enclosures")
 */
class Enclosure
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @var Collection
     * @ORM\OneToMany(targetEntity="App\CoreBundle\Entity\Dinosaur", mappedBy="enclosure", cascade={"persist"})
     */
    private $dinosaurs;

    /**
     * @var Collection|Security[]
     * @ORM\OneToMany(targetEntity="App\CoreBundle\Entity\Security", mappedBy="enclosure", cascade={"persist"})
     */
    private $securities;

    /**
     * @param bool $withBasicSecurity
     */
    public function __construct(bool $withBasicSecurity = false)
    {
        $this->dinosaurs  = new ArrayCollection();
        $this->securities = new ArrayCollection();

        if ($withBasicSecurity) {
            $this->addSecurity(new Security('Fence', true, $this));
        }
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection
     */
    public function getDinosaurs(): Collection
    {
        return $this->dinosaurs;
    }

    /**
     * @param Dinosaur $dinosaur
     *
     * @throws DinosaursAreRunningRampantException
     * @throws NotABuffetException
     */
    public function addDinosaur(Dinosaur $dinosaur)
    {
        if (!$this->isSecurityActive()) {
            throw new DinosaursAreRunningRampantException('Are you craaazy?!?');
        }

        if (!$this->canAddDinosaur($dinosaur)) {
            throw new NotABuffetException();
        }

        $this->dinosaurs[] = $dinosaur;
    }

    /**
     * @param Security $security
     */
    public function addSecurity(Security $security)
    {
        $this->securities[] = $security;
    }

    /**
     * @param Dinosaur $dinosaur
     *
     * @return bool
     */
    private function canAddDinosaur(Dinosaur $dinosaur): bool
    {
        return count($this->dinosaurs) === 0 || $this->dinosaurs->first()->isCarnivorous() === $dinosaur->isCarnivorous();
    }

    /**
     * @return bool
     */
    public function isSecurityActive(): bool
    {
        foreach ($this->securities as $security) {
            if ($security->getIsActive()) {
                return true;
            }
        }

        return false;
    }

    /**
     * @return Collection
     */
    public function getSecurities(): Collection
    {
        return $this->securities;
    }

    /**
     * @return int
     */
    public function getDinosaurCount(): int
    {
        return $this->dinosaurs->count();
    }
}

src/CoreBundle/Controller/DefaultController.php
<?php declare(strict_types=1);

namespace App\CoreBundle\Controller;

use App\CoreBundle\Entity\Enclosure;
use App\CoreBundle\Factory\DinosaurFactory;
use App\CoreBundle\Repository\EnclosureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/default", name="app_core_default_")
 */
class DefaultController extends AbstractController
{
    /**
     * @Route("/main", name="main")
     *
     * @param EnclosureRepository $enclosureRepository
     *
     * @return Response
     */
    public function main(EnclosureRepository $enclosureRepository): Response
    {
        return $this->render('@AppCore/Default/index.html.twig', [
            'enclosures' => $enclosureRepository->findAll(),
        ]);
    }

    /**
     * @Route("/grow", name="grow_dinosaur", methods={"POST"})
     *
     * @param Request         $request
     * @param DinosaurFactory $dinosaurFactory
     *
     * @throws \Exception
     *
     * @return RedirectResponse
     */
    public function growAction(Request $request, DinosaurFactory $dinosaurFactory): RedirectResponse
    {
        $manager = $this->getDoctrine()->getManager();

        $enclosure = $manager->getRepository(Enclosure::class)
            ->find($request->request->get('enclosure'));

        $specification = $request->request->get('specification');
        $dinosaur = $dinosaurFactory->growFromSpecification($specification);

        $dinosaur->setEnclosure($enclosure);
        $enclosure->addDinosaur($dinosaur);

        $manager->flush();

        $this->addFlash('success', sprintf(
            'Grew a %s in enclosure #%d',
            mb_strtolower($specification),
            $enclosure->getId()
        ));

        return $this->redirectToRoute('app_core_default_main');
    }
}

src/CoreBundle/Resources/views/Default/_newDinoForm.html.twig
<form action="{{ url('app_core_default_grow_dinosaur') }}" method="POST">
    <div class="row">
        <div class="column">
            <label for="enclosure">Enclosure</label>
            <select name="enclosure" id="enclosure">
                {% for enclosure in enclosures %}
                    <option value="{{ enclosure.id }}">Enclosure #{{ enclosure.id }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="column">
            <label for="specification">Dino description</label>
            <input type="text" id="specification" name="specification" placeholder="Small carnivorous dino friend" />
        </div>

        <div class="column">
            <label for="">&nbsp;</label>
            <input type="submit" class="button" value="Grow dinosaur" />
        </div>
    </div>
</form>

src/CoreBundle/Resources/views/Default/index.html.twig
{% extends '@AppDesign/HomePage/base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="{{ asset('bundles/appcore/css/normalize.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/appcore/css/milligram.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bundles/appcore/css/main.css') }}">
{% endblock %}

{% block body %}
    {{ include('@AppCore/Default/_newDinoForm.html.twig') }}

    <h3>Enclosures</h3>

    <table class="table-enclosures">
        <tbody>
        {% for enclosure in enclosures %}
            <tr id="enclosure-{{ enclosure.id }}">
                <td>Enclosure #{{ enclosure.id }}</td>
                <td>
                    Contains <strong>{{ enclosure.dinosaurCount }}</strong> dinosaur(s)
                </td>
                <td>
                    {% if enclosure.isSecurityActive %}
                        🔒 Security active!
                    {% else %}
                        <button class="button button-alarm">Sound alarm !!!</button>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}